eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8090/eureka
server:
    port: 8084
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useSSL=false&user=root&password=MySql@123
    jpa:
        hibernate:
            ddl-auto: create    
