eureka:
    client:
        serviceUrl:
            defaultZone: https://eurekaserviceregistry.cfapps.io/

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useSSL=false&user=root&password=MySql@123
    jpa:
        hibernate:
            ddl-auto: create    
